image: linagora/node-test-base:8

stages:
  - test
  - swagger
  - deploy-swagger
  - deploy_dev

test:
  stage: test
  tags:
    - docker
  image: docker-registry.linagora.com:5000/public-releases/openpaas-esn-test-helper:1.0.0
  services:
    - mongo:3.4
    - elasticsearch:2.4
    - redis:3
    - rabbitmq:3.6
    - linagora/esn-sabre:latest
  script:
    - npm i
    - npm update
    - bower i --allow-root
    - grunt --chunk=1 --ci

swagger:
  stage: swagger
  tags:
    - docker
  script:
    - npm i
    - npm prune
    - ./node_modules/.bin/grunt swagger-generate
  artifacts:
    paths:
      - ./doc/REST_API/swagger/group-swagger.json

deploy-swagger:
  stage: deploy-swagger
  tags:
    - deployment
    - api.open-paas.org
    - shell
  environment:
    name: api
    url: https://api.open-paas.org
  only:
    - master@linagora/lgs/openpaas/linagora.esn.group
  script:
    - perl -i -pe's/"host":"localhost:8080"/"schemes":["https"],"host":"demo.open-paas.org"/' ./doc/REST_API/swagger/group-swagger.json
    - cp ./doc/REST_API/swagger/group-swagger.json /var/www/html

deploy_dev:
  stage: deploy_dev
  tags:
    - dev.open-paas.org
    - deployment
  environment:
    name: dev
    url: https://dev.open-paas.org
  only:
    - master
  script:
    - cd /srv/${CI_PROJECT_NAME}
    - git fetch --all
    - git checkout ${CI_COMMIT_SHA}
    - npm install --production
    - npm update --production
    - npm prune
    - bower install --production
    - bower prune
    - git checkout -- .
    - sudo /etc/init.d/rse.dev restart
